package automation

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/chichex/cvm/internal/config"
	"github.com/chichex/cvm/internal/kb"
)

func TestRecordSessionEndQueuesCandidatesByThresholds(t *testing.T) {
	t.Setenv("CVM_MAINTAIN_MIN_ENTRIES", "4")
	t.Setenv("CVM_MAINTAIN_STALE_THRESHOLD", "2")
	t.Setenv("CVM_MAINTAIN_SESSION_THRESHOLD", "2")
	t.Setenv("CVM_EVOLVE_TAG_THRESHOLD", "3")
	t.Setenv("CVM_EVOLVE_SESSION_THRESHOLD", "2")

	state := &State{
		SessionsSinceMaintain: 1,
		SessionsSinceEvolve:   1,
	}

	global := Snapshot{Scope: config.ScopeGlobal, Total: 5, Stale: 2, Tagged: 3}
	local := Snapshot{Scope: config.ScopeLocal, ProjectPath: "/tmp/project", Total: 1, Stale: 0, Tagged: 0}

	queued := state.RecordSessionEnd(global, local, true)
	if len(queued) != 2 {
		t.Fatalf("expected maintain and evolve candidates, got %d", len(queued))
	}
	if state.LastRetroQueuedAt.IsZero() {
		t.Fatal("expected retro timestamp to be recorded")
	}
}

func TestRunPendingAppliesMaintainAndClearsCandidate(t *testing.T) {
	home := t.TempDir()
	project := t.TempDir()
	t.Setenv("HOME", home)

	now := time.Now().AddDate(0, 0, -45)
	seedDocument(t, config.ScopeLocal, project, kb.Document{
		Entry: kb.Entry{
			Key:       "Old-Gotcha",
			Tags:      []string{"Gotcha", "Build"},
			Enabled:   true,
			CreatedAt: now,
			UpdatedAt: now,
		},
		Body: "This is stale and should be auto disabled.",
	})
	seedDocument(t, config.ScopeLocal, project, kb.Document{
		Entry: kb.Entry{
			Key:       "dup-one",
			Tags:      []string{"learning", "Build"},
			Enabled:   true,
			CreatedAt: time.Now().Add(-2 * time.Hour),
			UpdatedAt: time.Now().Add(-2 * time.Hour),
		},
		Body: "Same body",
	})
	seedDocument(t, config.ScopeLocal, project, kb.Document{
		Entry: kb.Entry{
			Key:       "dup-two",
			Tags:      []string{"learning", "build"},
			Enabled:   true,
			CreatedAt: time.Now().Add(-1 * time.Hour),
			UpdatedAt: time.Now().Add(-1 * time.Hour),
		},
		Body: "Same body",
	})

	state := &State{}
	state.enqueue(Candidate{
		Kind:        "maintain",
		Scope:       string(config.ScopeLocal),
		ProjectPath: project,
		Reason:      "enough stale docs",
	})
	if err := state.Save(); err != nil {
		t.Fatalf("save state: %v", err)
	}

	runs, err := RunPending(10)
	if err != nil {
		t.Fatalf("run pending: %v", err)
	}
	if len(runs) != 1 || runs[0].Status != "applied" {
		t.Fatalf("unexpected runs: %+v", runs)
	}

	reloaded, err := Load()
	if err != nil {
		t.Fatalf("reload state: %v", err)
	}
	if reloaded.PendingCount() != 0 {
		t.Fatalf("expected candidate to clear, got %d pending", reloaded.PendingCount())
	}

	docs, err := kb.LoadDocuments(config.ScopeLocal, project)
	if err != nil {
		t.Fatalf("load docs: %v", err)
	}

	docByKey := make(map[string]kb.Document)
	for _, doc := range docs {
		docByKey[doc.Entry.Key] = doc
	}

	if docByKey["Old-Gotcha"].Entry.Enabled {
		t.Fatal("expected stale entry to be disabled")
	}
	if !containsTag(docByKey["Old-Gotcha"].Entry.Tags, "stale") {
		t.Fatalf("expected stale tag, got %v", docByKey["Old-Gotcha"].Entry.Tags)
	}

	if docByKey["dup-one"].Entry.Enabled && docByKey["dup-two"].Entry.Enabled {
		t.Fatal("expected one duplicate to be disabled")
	}

	if _, err := os.Stat(RunPath(runs[0])); err != nil {
		t.Fatalf("expected run log: %v", err)
	}
}

func TestRunPendingGeneratesAndInstallsSkill(t *testing.T) {
	home := t.TempDir()
	project := t.TempDir()
	t.Setenv("HOME", home)

	now := time.Now()
	seedDocument(t, config.ScopeLocal, project, kb.Document{
		Entry: kb.Entry{
			Key:       "build-gotcha",
			Tags:      []string{"gotcha", "build"},
			Enabled:   true,
			CreatedAt: now,
			UpdatedAt: now,
		},
		Body: "Remember to clear generated files before rebuilding.",
	})
	seedDocument(t, config.ScopeLocal, project, kb.Document{
		Entry: kb.Entry{
			Key:       "build-learning",
			Tags:      []string{"learning", "build"},
			Enabled:   true,
			CreatedAt: now.Add(time.Minute),
			UpdatedAt: now.Add(time.Minute),
		},
		Body: "Use the project Makefile before ad-hoc commands.",
	})

	state := &State{}
	candidate := state.enqueue(Candidate{
		Kind:        "evolve",
		Scope:       string(config.ScopeLocal),
		ProjectPath: project,
		Reason:      "repeated build learnings",
	})
	if err := state.Save(); err != nil {
		t.Fatalf("save state: %v", err)
	}

	runs, err := RunPending(10)
	if err != nil {
		t.Fatalf("run pending: %v", err)
	}
	if len(runs) != 1 || runs[0].Status != "applied" {
		t.Fatalf("unexpected runs: %+v", runs)
	}

	proposal, err := os.ReadFile(filepath.Join(proposalsDir(), "auto-build-workflow.md"))
	if err != nil {
		t.Fatalf("read proposal: %v", err)
	}
	if !strings.Contains(string(proposal), autoGeneratedMarker) {
		t.Fatalf("expected auto-generated marker in proposal: %s", string(proposal))
	}

	skillPath := filepath.Join(project, ".claude", "skills", "auto-build-workflow", "SKILL.md")
	skillContent, err := os.ReadFile(skillPath)
	if err != nil {
		t.Fatalf("read installed skill: %v", err)
	}
	if !strings.Contains(string(skillContent), "build") {
		t.Fatalf("expected build-specific skill content: %s", string(skillContent))
	}

	artifact, err := ReadArtifact(candidate.ID)
	if err != nil {
		t.Fatalf("read artifact: %v", err)
	}
	if !strings.Contains(artifact, "Automatic Resolution") {
		t.Fatalf("expected artifact resolution section: %s", artifact)
	}
}

func seedDocument(t *testing.T, scope config.Scope, project string, doc kb.Document) {
	t.Helper()
	if err := kb.SaveDocument(scope, project, doc); err != nil {
		t.Fatalf("seed document %s: %v", doc.Entry.Key, err)
	}
}

func containsTag(tags []string, want string) bool {
	for _, tag := range tags {
		if strings.EqualFold(tag, want) {
			return true
		}
	}
	return false
}
