package automation

import (
	"crypto/sha1"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/chichex/cvm/internal/config"
	"github.com/chichex/cvm/internal/kb"
)

const (
	defaultMaintainMinEntries       = 8
	defaultMaintainStaleThreshold   = 3
	defaultMaintainSessionThreshold = 5
	defaultEvolveTagThreshold       = 6
	defaultEvolveSessionThreshold   = 3
	defaultAutomationRunLimit       = 4
	autoGeneratedMarker             = "<!-- cvm:auto-generated -->"
)

type Candidate struct {
	ID          string    `json:"id"`
	Kind        string    `json:"kind"`
	Scope       string    `json:"scope"`
	ProjectPath string    `json:"project_path,omitempty"`
	Reason      string    `json:"reason"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	Hits        int       `json:"hits"`
}

type Action struct {
	Type   string `json:"type"`
	Target string `json:"target"`
	Status string `json:"status"`
	Detail string `json:"detail,omitempty"`
}

type Run struct {
	ID          string    `json:"id"`
	CandidateID string    `json:"candidate_id"`
	Kind        string    `json:"kind"`
	Scope       string    `json:"scope"`
	ProjectPath string    `json:"project_path,omitempty"`
	StartedAt   time.Time `json:"started_at"`
	CompletedAt time.Time `json:"completed_at"`
	Status      string    `json:"status"`
	Summary     string    `json:"summary"`
	Error       string    `json:"error,omitempty"`
	Actions     []Action  `json:"actions,omitempty"`
	Artifact    string    `json:"artifact,omitempty"`
}

type State struct {
	TotalSessions         int         `json:"total_sessions"`
	SessionsSinceMaintain int         `json:"sessions_since_maintain"`
	SessionsSinceEvolve   int         `json:"sessions_since_evolve"`
	LastSessionEnd        time.Time   `json:"last_session_end,omitempty"`
	LastRetroQueuedAt     time.Time   `json:"last_retro_queued_at,omitempty"`
	LastAutomationRunAt   time.Time   `json:"last_automation_run_at,omitempty"`
	Pending               []Candidate `json:"pending,omitempty"`
	Runs                  []Run       `json:"runs,omitempty"`
}

type Snapshot struct {
	Scope       config.Scope
	ProjectPath string
	Total       int
	Stale       int
	Tagged      int
}

func statePath() string {
	return filepath.Join(config.CvmHome(), "automation", "state.json")
}

func artifactsDir() string {
	return filepath.Join(config.CvmHome(), "automation", "artifacts")
}

func proposalsDir() string {
	return filepath.Join(config.CvmHome(), "automation", "proposals")
}

func runsDir() string {
	return filepath.Join(config.CvmHome(), "automation", "runs")
}

func Load() (*State, error) {
	state := &State{}
	data, err := os.ReadFile(statePath())
	if err != nil {
		if os.IsNotExist(err) {
			return state, nil
		}
		return nil, err
	}
	if err := json.Unmarshal(data, state); err != nil {
		return nil, err
	}
	return state, nil
}

func (s *State) Save() error {
	if err := os.MkdirAll(filepath.Dir(statePath()), 0755); err != nil {
		return err
	}
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(statePath(), data, 0644)
}

func (s *State) RecordSessionEnd(global, local Snapshot, retroQueued bool) []Candidate {
	s.TotalSessions++
	s.SessionsSinceMaintain++
	s.SessionsSinceEvolve++
	s.LastSessionEnd = time.Now()
	if retroQueued {
		s.LastRetroQueuedAt = s.LastSessionEnd
	}

	var queued []Candidate
	for _, snapshot := range []Snapshot{global, local} {
		if candidate, ok := s.shouldQueueMaintain(snapshot); ok {
			queued = append(queued, s.enqueue(candidate))
			s.SessionsSinceMaintain = 0
		}
		if candidate, ok := s.shouldQueueEvolve(snapshot); ok {
			queued = append(queued, s.enqueue(candidate))
			s.SessionsSinceEvolve = 0
		}
	}

	return queued
}

func (s *State) PendingCount() int {
	return len(s.Pending)
}

func ArtifactPath(candidate Candidate) string {
	return filepath.Join(artifactsDir(), candidate.ID+".md")
}

func RunPath(run Run) string {
	return filepath.Join(runsDir(), run.ID+".json")
}

func ProposalPath(candidate Candidate, skillName string) string {
	return filepath.Join(proposalsDir(), skillName+".md")
}

func ReadArtifact(id string) (string, error) {
	data, err := os.ReadFile(filepath.Join(artifactsDir(), id+".md"))
	if err != nil {
		if os.IsNotExist(err) {
			return "", fmt.Errorf("artifact %q not found", id)
		}
		return "", err
	}
	return string(data), nil
}

func ReadRun(id string) (Run, error) {
	data, err := os.ReadFile(filepath.Join(runsDir(), id+".json"))
	if err != nil {
		if os.IsNotExist(err) {
			return Run{}, fmt.Errorf("run %q not found", id)
		}
		return Run{}, err
	}
	var run Run
	if err := json.Unmarshal(data, &run); err != nil {
		return Run{}, err
	}
	return run, nil
}

func MaterializePending(state *State) error {
	if err := os.MkdirAll(artifactsDir(), 0755); err != nil {
		return err
	}

	for i := range state.Pending {
		if err := materializeCandidate(state.Pending[i]); err != nil {
			return err
		}
	}

	return nil
}

func RunPending(limit int) ([]Run, error) {
	if limit <= 0 {
		limit = envInt("CVM_AUTOMATION_RUN_LIMIT", defaultAutomationRunLimit)
	}

	state, err := Load()
	if err != nil {
		return nil, err
	}
	if len(state.Pending) == 0 {
		return nil, nil
	}

	if err := os.MkdirAll(runsDir(), 0755); err != nil {
		return nil, err
	}
	if err := os.MkdirAll(proposalsDir(), 0755); err != nil {
		return nil, err
	}

	candidates := append([]Candidate(nil), state.Pending...)
	sort.Slice(candidates, func(i, j int) bool {
		if candidates[i].UpdatedAt.Equal(candidates[j].UpdatedAt) {
			return candidates[i].ID < candidates[j].ID
		}
		return candidates[i].UpdatedAt.Before(candidates[j].UpdatedAt)
	})
	if len(candidates) > limit {
		candidates = candidates[:limit]
	}

	var runs []Run
	for _, candidate := range candidates {
		run := runCandidate(candidate)
		runs = append(runs, run)
		state.recordRun(run)

		if run.Status == "failed" {
			continue
		}
		state.removePending(candidate.ID)
	}

	if len(runs) > 0 {
		state.LastAutomationRunAt = time.Now()
	}
	if err := MaterializePending(state); err != nil {
		return runs, err
	}
	if err := state.Save(); err != nil {
		return runs, err
	}

	return runs, nil
}

func (s *State) RecentRuns(limit int) []Run {
	if len(s.Runs) == 0 {
		return nil
	}
	out := append([]Run(nil), s.Runs...)
	sort.Slice(out, func(i, j int) bool {
		if out[i].CompletedAt.Equal(out[j].CompletedAt) {
			return out[i].ID > out[j].ID
		}
		return out[i].CompletedAt.After(out[j].CompletedAt)
	})
	if limit > 0 && len(out) > limit {
		out = out[:limit]
	}
	return out
}

func (s *State) shouldQueueMaintain(snapshot Snapshot) (Candidate, bool) {
	if snapshot.Total < envInt("CVM_MAINTAIN_MIN_ENTRIES", defaultMaintainMinEntries) {
		return Candidate{}, false
	}
	if snapshot.Stale < envInt("CVM_MAINTAIN_STALE_THRESHOLD", defaultMaintainStaleThreshold) &&
		s.SessionsSinceMaintain < envInt("CVM_MAINTAIN_SESSION_THRESHOLD", defaultMaintainSessionThreshold) {
		return Candidate{}, false
	}

	reason := fmt.Sprintf("%d KB entries, %d stale references", snapshot.Total, snapshot.Stale)
	if snapshot.Stale < envInt("CVM_MAINTAIN_STALE_THRESHOLD", defaultMaintainStaleThreshold) {
		reason = fmt.Sprintf("%d sessions since last maintenance trigger with %d KB entries", s.SessionsSinceMaintain, snapshot.Total)
	}

	return Candidate{
		Kind:        "maintain",
		Scope:       string(snapshot.Scope),
		ProjectPath: snapshot.ProjectPath,
		Reason:      reason,
	}, true
}

func (s *State) shouldQueueEvolve(snapshot Snapshot) (Candidate, bool) {
	if snapshot.Tagged < envInt("CVM_EVOLVE_TAG_THRESHOLD", defaultEvolveTagThreshold) {
		return Candidate{}, false
	}
	if s.SessionsSinceEvolve < envInt("CVM_EVOLVE_SESSION_THRESHOLD", defaultEvolveSessionThreshold) {
		return Candidate{}, false
	}

	return Candidate{
		Kind:        "evolve",
		Scope:       string(snapshot.Scope),
		ProjectPath: snapshot.ProjectPath,
		Reason:      fmt.Sprintf("%d learning/gotcha/decision KB entries across recent sessions", snapshot.Tagged),
	}, true
}

func (s *State) enqueue(candidate Candidate) Candidate {
	now := time.Now()
	candidate.ID = candidateID(candidate.Kind, candidate.Scope, candidate.ProjectPath)
	candidate.CreatedAt = now
	candidate.UpdatedAt = now
	candidate.Hits = 1

	for i, existing := range s.Pending {
		if existing.ID == candidate.ID {
			existing.Reason = candidate.Reason
			existing.UpdatedAt = now
			existing.Hits++
			s.Pending[i] = existing
			return existing
		}
	}

	s.Pending = append(s.Pending, candidate)
	return candidate
}

func (s *State) removePending(id string) {
	for i, candidate := range s.Pending {
		if candidate.ID == id {
			s.Pending = append(s.Pending[:i], s.Pending[i+1:]...)
			return
		}
	}
}

func (s *State) recordRun(run Run) {
	s.Runs = append([]Run{run}, s.Runs...)
	if len(s.Runs) > 20 {
		s.Runs = s.Runs[:20]
	}
}

func envInt(name string, fallback int) int {
	raw := os.Getenv(name)
	if raw == "" {
		return fallback
	}
	value, err := strconv.Atoi(raw)
	if err != nil || value <= 0 {
		return fallback
	}
	return value
}

func BuildArtifact(candidate Candidate) (string, error) {
	scope := config.Scope(candidate.Scope)
	projectPath := candidate.ProjectPath
	entries, err := kb.List(scope, projectPath, "")
	if err != nil {
		return "", err
	}

	total, enabled, stale, err := kb.Stats(scope, projectPath)
	if err != nil {
		return "", err
	}

	var details []string
	switch candidate.Kind {
	case "maintain":
		details = maintainDetails(entries)
	case "evolve":
		details = evolveDetails(entries)
	default:
		details = []string{"No detail formatter available for this candidate kind."}
	}

	scopeLabel := candidate.Scope
	if candidate.ProjectPath != "" {
		scopeLabel = fmt.Sprintf("%s (%s)", candidate.Scope, candidate.ProjectPath)
	}

	var sb strings.Builder
	sb.WriteString(fmt.Sprintf("# Automation Candidate: %s\n\n", candidate.ID))
	sb.WriteString(fmt.Sprintf("- Kind: `%s`\n", candidate.Kind))
	sb.WriteString(fmt.Sprintf("- Scope: `%s`\n", scopeLabel))
	sb.WriteString(fmt.Sprintf("- Reason: %s\n", candidate.Reason))
	sb.WriteString(fmt.Sprintf("- Hits: %d\n", candidate.Hits))
	sb.WriteString(fmt.Sprintf("- Created: %s\n", candidate.CreatedAt.Format(time.RFC3339)))
	sb.WriteString(fmt.Sprintf("- Updated: %s\n", candidate.UpdatedAt.Format(time.RFC3339)))
	sb.WriteString("\n## Snapshot\n\n")
	sb.WriteString(fmt.Sprintf("- KB entries: %d\n", total))
	sb.WriteString(fmt.Sprintf("- Enabled entries: %d\n", enabled))
	sb.WriteString(fmt.Sprintf("- Stale entries: %d\n", stale))
	sb.WriteString("\n## Evidence\n\n")
	for _, line := range details {
		sb.WriteString(fmt.Sprintf("- %s\n", line))
	}
	sb.WriteString("\n## Automatic Resolution\n\n")
	switch candidate.Kind {
	case "maintain":
		sb.WriteString("- The automation runner normalizes tags, disables stale entries, and suppresses exact duplicates unless they are protected.\n")
	case "evolve":
		sb.WriteString("- The automation runner installs or updates an auto-generated skill using repeated KB patterns for this scope.\n")
	default:
		sb.WriteString("- The automation runner will attempt to resolve this candidate automatically.\n")
	}

	return sb.String(), nil
}

func candidateID(kind, scope, projectPath string) string {
	if projectPath == "" {
		return fmt.Sprintf("%s-%s", kind, scope)
	}
	sum := sha1.Sum([]byte(projectPath))
	return fmt.Sprintf("%s-%s-%x", kind, scope, sum[:4])
}

func maintainDetails(entries []kb.Entry) []string {
	if len(entries) == 0 {
		return []string{"KB is empty; no maintenance evidence available."}
	}

	now := time.Now()
	thirtyDaysAgo := now.AddDate(0, 0, -30)
	var staleEntries []kb.Entry
	tagCounts := make(map[string]int)
	for _, entry := range entries {
		for _, tag := range entry.Tags {
			tagCounts[tag]++
		}
		if isStale(entry, thirtyDaysAgo) {
			staleEntries = append(staleEntries, entry)
		}
	}

	sort.Slice(staleEntries, func(i, j int) bool {
		return staleReferenceTime(staleEntries[i]).Before(staleReferenceTime(staleEntries[j]))
	})

	lines := make([]string, 0, 8)
	for i, entry := range staleEntries {
		if i == 5 {
			break
		}
		lines = append(lines, fmt.Sprintf("Stale: `%s` [%s]", entry.Key, strings.Join(entry.Tags, ", ")))
	}

	for _, summary := range topTagSummaries(tagCounts, 3) {
		lines = append(lines, summary)
	}

	if len(lines) == 0 {
		lines = append(lines, "Threshold met by session count, but no individual stale entries ranked yet.")
	}

	return lines
}

func evolveDetails(entries []kb.Entry) []string {
	type taggedEntry struct {
		entry kb.Entry
		tag   string
	}

	var relevant []taggedEntry
	for _, entry := range entries {
		for _, tag := range entry.Tags {
			switch strings.ToLower(tag) {
			case "learning", "gotcha", "decision":
				relevant = append(relevant, taggedEntry{entry: entry, tag: strings.ToLower(tag)})
				break
			}
		}
	}

	sort.Slice(relevant, func(i, j int) bool {
		return relevant[i].entry.UpdatedAt.After(relevant[j].entry.UpdatedAt)
	})

	lines := make([]string, 0, 6)
	for i, item := range relevant {
		if i == 5 {
			break
		}
		lines = append(lines, fmt.Sprintf("Recent `%s`: `%s` [%s]", item.tag, item.entry.Key, strings.Join(item.entry.Tags, ", ")))
	}

	if len(lines) == 0 {
		lines = append(lines, "Threshold met, but no tagged learning/gotcha/decision entries were found.")
	}

	return lines
}

func topTagSummaries(tagCounts map[string]int, limit int) []string {
	type tagCount struct {
		tag   string
		count int
	}

	var pairs []tagCount
	for tag, count := range tagCounts {
		pairs = append(pairs, tagCount{tag: tag, count: count})
	}
	sort.Slice(pairs, func(i, j int) bool {
		if pairs[i].count == pairs[j].count {
			return pairs[i].tag < pairs[j].tag
		}
		return pairs[i].count > pairs[j].count
	})

	lines := make([]string, 0, limit)
	for i, pair := range pairs {
		if i == limit {
			break
		}
		lines = append(lines, fmt.Sprintf("Tag density: `%s` appears in %d entries", pair.tag, pair.count))
	}
	return lines
}

func isStale(entry kb.Entry, threshold time.Time) bool {
	if !entry.LastReferenced.IsZero() {
		return entry.LastReferenced.Before(threshold)
	}
	return entry.CreatedAt.Before(threshold)
}

func staleReferenceTime(entry kb.Entry) time.Time {
	if !entry.LastReferenced.IsZero() {
		return entry.LastReferenced
	}
	return entry.CreatedAt
}

func runCandidate(candidate Candidate) Run {
	_ = materializeCandidate(candidate)

	run := Run{
		ID:          fmt.Sprintf("%s-%s", candidate.ID, time.Now().Format("20060102-150405")),
		CandidateID: candidate.ID,
		Kind:        candidate.Kind,
		Scope:       candidate.Scope,
		ProjectPath: candidate.ProjectPath,
		StartedAt:   time.Now(),
		Artifact:    ArtifactPath(candidate),
	}

	var (
		err     error
		summary string
		actions []Action
		status  string
	)

	switch candidate.Kind {
	case "maintain":
		summary, actions, err = applyMaintain(candidate)
	case "evolve":
		summary, actions, err = applyEvolve(candidate)
	default:
		summary = "no handler for candidate kind"
		status = "skipped"
	}

	run.CompletedAt = time.Now()
	run.Actions = actions

	if err != nil {
		run.Status = "failed"
		run.Error = err.Error()
		run.Summary = "automation run failed"
	} else {
		if status == "" {
			if len(actions) == 0 {
				status = "skipped"
			} else {
				status = "applied"
			}
		}
		run.Status = status
		run.Summary = summary
	}

	_ = writeRun(run)
	return run
}

func materializeCandidate(candidate Candidate) error {
	if err := os.MkdirAll(artifactsDir(), 0755); err != nil {
		return err
	}
	body, err := BuildArtifact(candidate)
	if err != nil {
		return err
	}
	return os.WriteFile(ArtifactPath(candidate), []byte(body), 0644)
}

func applyMaintain(candidate Candidate) (string, []Action, error) {
	scope := config.Scope(candidate.Scope)
	docs, err := kb.LoadDocuments(scope, candidate.ProjectPath)
	if err != nil {
		return "", nil, err
	}
	if len(docs) == 0 {
		return "no KB documents to maintain", nil, nil
	}

	now := time.Now()
	threshold := now.AddDate(0, 0, -30)
	actions := make([]Action, 0, len(docs))

	duplicateGroups := make(map[string][]int)
	for i, doc := range docs {
		signature := normalizedBody(doc.Body)
		if signature != "" {
			duplicateGroups[signature] = append(duplicateGroups[signature], i)
		}
	}

	canonicalKeys := make(map[string]map[string]bool)
	for signature, indexes := range duplicateGroups {
		if len(indexes) < 2 {
			continue
		}
		sort.Slice(indexes, func(i, j int) bool {
			left := docs[indexes[i]].Entry
			right := docs[indexes[j]].Entry
			if left.Enabled != right.Enabled {
				return left.Enabled
			}
			if left.UpdatedAt.Equal(right.UpdatedAt) {
				return left.Key < right.Key
			}
			return left.UpdatedAt.After(right.UpdatedAt)
		})
		keepers := make(map[string]bool)
		keepers[docs[indexes[0]].Entry.Key] = true
		canonicalKeys[signature] = keepers
	}

	for _, doc := range docs {
		changed := false

		normalizedTags := normalizeTags(doc.Entry.Tags)
		if !equalStrings(normalizedTags, doc.Entry.Tags) {
			doc.Entry.Tags = normalizedTags
			doc.Entry.UpdatedAt = now
			actions = append(actions, Action{
				Type:   "normalize-tags",
				Target: doc.Entry.Key,
				Status: "applied",
				Detail: strings.Join(normalizedTags, ", "),
			})
			changed = true
		}

		signature := normalizedBody(doc.Body)
		if keepers, ok := canonicalKeys[signature]; ok && !keepers[doc.Entry.Key] && !isProtected(doc.Entry.Tags) {
			if doc.Entry.Enabled {
				doc.Entry.Enabled = false
				doc.Entry.UpdatedAt = now
				actions = append(actions, Action{
					Type:   "disable-duplicate",
					Target: doc.Entry.Key,
					Status: "applied",
					Detail: "exact duplicate body suppressed",
				})
				changed = true
			}
			tags := appendUnique(doc.Entry.Tags, "duplicate", "auto-disabled")
			if !equalStrings(tags, doc.Entry.Tags) {
				doc.Entry.Tags = tags
				doc.Entry.UpdatedAt = now
				changed = true
			}
		}

		if isStale(doc.Entry, threshold) && doc.Entry.Enabled && !isProtected(doc.Entry.Tags) {
			doc.Entry.Enabled = false
			doc.Entry.Tags = appendUnique(doc.Entry.Tags, "stale", "auto-disabled")
			doc.Entry.UpdatedAt = now
			actions = append(actions, Action{
				Type:   "disable-stale",
				Target: doc.Entry.Key,
				Status: "applied",
				Detail: "entry auto-disabled after staleness threshold",
			})
			changed = true
		}

		if changed {
			if err := kb.SaveDocument(scope, candidate.ProjectPath, doc); err != nil {
				return "", actions, err
			}
		}
	}

	if len(actions) == 0 {
		return "maintenance found nothing to change", actions, nil
	}
	return fmt.Sprintf("applied %d maintenance change(s)", len(actions)), actions, nil
}

func applyEvolve(candidate Candidate) (string, []Action, error) {
	scope := config.Scope(candidate.Scope)
	docs, err := kb.LoadDocuments(scope, candidate.ProjectPath)
	if err != nil {
		return "", nil, err
	}

	relevant := collectRelevantDocs(docs)
	if len(relevant) == 0 {
		return "no learning/gotcha/decision docs available for skill generation", nil, nil
	}

	skillName := deriveSkillName(relevant)
	skillContent := buildSkillContent(skillName, relevant)

	actualSkillName, targetSkillPath, action, err := installSkill(candidate, skillName, skillContent)
	if err != nil {
		return "", nil, err
	}

	proposal := ProposalPath(candidate, actualSkillName)
	if err := os.MkdirAll(filepath.Dir(proposal), 0755); err != nil {
		return "", nil, err
	}
	if err := os.WriteFile(proposal, []byte(skillContent), 0644); err != nil {
		return "", nil, err
	}

	recordKey := fmt.Sprintf("automation-skill-%s", actualSkillName)
	recordBody := fmt.Sprintf("Auto-generated skill /%s from repeated KB patterns and installed at %s.", actualSkillName, targetSkillPath)
	if err := kb.Put(scope, candidate.ProjectPath, recordKey, recordBody, []string{"automation", "evolve", "skill"}); err != nil {
		return "", []Action{action}, err
	}

	actions := []Action{
		{
			Type:   "write-proposal",
			Target: proposal,
			Status: "applied",
			Detail: "automation proposal written",
		},
		action,
		{
			Type:   "record-kb",
			Target: recordKey,
			Status: "applied",
			Detail: "automation skill installation recorded in KB",
		},
	}

	return fmt.Sprintf("generated skill /%s and installed it automatically", actualSkillName), actions, nil
}

func writeRun(run Run) error {
	data, err := json.MarshalIndent(run, "", "  ")
	if err != nil {
		return err
	}
	return os.WriteFile(RunPath(run), data, 0644)
}

func normalizedBody(body string) string {
	body = strings.ToLower(strings.TrimSpace(body))
	if body == "" {
		return ""
	}
	fields := strings.Fields(body)
	return strings.Join(fields, " ")
}

func normalizeTags(tags []string) []string {
	seen := make(map[string]bool)
	out := make([]string, 0, len(tags))
	for _, tag := range tags {
		normalized := strings.ToLower(strings.TrimSpace(tag))
		if normalized == "" || seen[normalized] {
			continue
		}
		seen[normalized] = true
		out = append(out, normalized)
	}
	sort.Strings(out)
	return out
}

func equalStrings(a, b []string) bool {
	if len(a) != len(b) {
		return false
	}
	for i := range a {
		if a[i] != b[i] {
			return false
		}
	}
	return true
}

func appendUnique(tags []string, extras ...string) []string {
	out := append([]string(nil), tags...)
	for _, extra := range extras {
		extra = strings.ToLower(strings.TrimSpace(extra))
		if extra == "" {
			continue
		}
		found := false
		for _, tag := range out {
			if tag == extra {
				found = true
				break
			}
		}
		if !found {
			out = append(out, extra)
		}
	}
	sort.Strings(out)
	return out
}

func isProtected(tags []string) bool {
	for _, tag := range tags {
		switch strings.ToLower(tag) {
		case "manual", "keep", "pinned", "no-auto", "auto-keep":
			return true
		}
	}
	return false
}

func collectRelevantDocs(docs []kb.Document) []kb.Document {
	var relevant []kb.Document
	for _, doc := range docs {
		for _, tag := range doc.Entry.Tags {
			switch strings.ToLower(tag) {
			case "learning", "gotcha", "decision":
				relevant = append(relevant, doc)
				goto next
			}
		}
	next:
	}
	sort.Slice(relevant, func(i, j int) bool {
		if relevant[i].Entry.UpdatedAt.Equal(relevant[j].Entry.UpdatedAt) {
			return relevant[i].Entry.Key < relevant[j].Entry.Key
		}
		return relevant[i].Entry.UpdatedAt.After(relevant[j].Entry.UpdatedAt)
	})
	return relevant
}

func deriveSkillName(docs []kb.Document) string {
	counts := make(map[string]int)
	for _, doc := range docs {
		for _, tag := range doc.Entry.Tags {
			normalized := strings.ToLower(strings.TrimSpace(tag))
			switch normalized {
			case "", "learning", "gotcha", "decision", "automation", "skill", "stale", "duplicate", "auto-disabled":
				continue
			}
			counts[normalized]++
		}
	}

	type pair struct {
		tag   string
		count int
	}
	var pairs []pair
	for tag, count := range counts {
		pairs = append(pairs, pair{tag: sanitizeSkillSegment(tag), count: count})
	}
	sort.Slice(pairs, func(i, j int) bool {
		if pairs[i].count == pairs[j].count {
			return pairs[i].tag < pairs[j].tag
		}
		return pairs[i].count > pairs[j].count
	})

	if len(pairs) == 0 || pairs[0].tag == "" {
		return "auto-kb-workflow"
	}
	name := "auto-" + pairs[0].tag + "-workflow"
	if len(pairs) > 1 && pairs[1].count == pairs[0].count && pairs[1].tag != "" && pairs[1].tag != pairs[0].tag {
		name = "auto-" + pairs[0].tag + "-" + pairs[1].tag + "-workflow"
	}
	return name
}

func buildSkillContent(skillName string, docs []kb.Document) string {
	var sb strings.Builder
	sb.WriteString(autoGeneratedMarker + "\n")
	sb.WriteString(fmt.Sprintf("Apply recurring KB patterns automatically for `%s` tasks.\n\n", skillName))
	sb.WriteString("## Context Signals\n\n")
	for i, doc := range docs {
		if i == 5 {
			break
		}
		sb.WriteString(fmt.Sprintf("- `%s`: %s\n", doc.Entry.Key, summarizeBody(doc.Body)))
	}
	sb.WriteString("\n## Process\n\n")
	sb.WriteString("1. Detect whether the current task overlaps with the recurring areas captured below.\n")
	sb.WriteString("2. Apply the repeated gotchas, learnings, and decisions before making code changes.\n")
	sb.WriteString("3. Reuse the existing workaround or pattern unless current evidence contradicts it.\n")
	sb.WriteString("4. If the task diverges from these patterns, record a new learning instead of forcing the old approach.\n")
	sb.WriteString("\n## Auto-Applied Patterns\n\n")
	for i, doc := range docs {
		if i == 5 {
			break
		}
		sb.WriteString(fmt.Sprintf("- `%s`: %s\n", doc.Entry.Key, summarizeBody(doc.Body)))
	}
	sb.WriteString("\n## MUST DO\n\n")
	sb.WriteString("- Reuse the proven patterns encoded in the referenced KB entries.\n")
	sb.WriteString("- Prefer the simplest known-good path before inventing a new workflow.\n")
	sb.WriteString("- Add a new KB learning if this skill stops matching reality.\n")
	sb.WriteString("\n## MUST NOT DO\n\n")
	sb.WriteString("- Do not override explicit user instructions with this skill.\n")
	sb.WriteString("- Do not apply stale patterns blindly when the codebase clearly changed.\n")
	sb.WriteString("- Do not create speculative follow-up automations from this skill alone.\n")
	return sb.String()
}

func sanitizeSkillSegment(tag string) string {
	tag = strings.ToLower(strings.TrimSpace(tag))
	tag = strings.ReplaceAll(tag, "_", "-")
	var b strings.Builder
	lastDash := false
	for _, r := range tag {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			b.WriteRune(r)
			lastDash = false
			continue
		}
		if !lastDash {
			b.WriteRune('-')
			lastDash = true
		}
	}
	return strings.Trim(b.String(), "-")
}

func summarizeBody(body string) string {
	body = strings.TrimSpace(body)
	if body == "" {
		return "No body available."
	}
	body = strings.ReplaceAll(body, "\n", " ")
	body = strings.Join(strings.Fields(body), " ")
	if len(body) > 160 {
		return body[:157] + "..."
	}
	return body
}

func installSkill(candidate Candidate, skillName, content string) (string, string, Action, error) {
	target := filepath.Join(skillRoot(candidate), skillName, "SKILL.md")
	if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
		return "", "", Action{}, err
	}

	if existing, err := os.ReadFile(target); err == nil {
		if !strings.Contains(string(existing), autoGeneratedMarker) {
			skillName = skillName + "-auto"
			target = filepath.Join(skillRoot(candidate), skillName, "SKILL.md")
			if err := os.MkdirAll(filepath.Dir(target), 0755); err != nil {
				return "", "", Action{}, err
			}
		}
	}

	if err := os.WriteFile(target, []byte(content), 0644); err != nil {
		return "", "", Action{}, err
	}

	return skillName, target, Action{
		Type:   "install-skill",
		Target: target,
		Status: "applied",
		Detail: "auto-generated skill installed",
	}, nil
}

func skillRoot(candidate Candidate) string {
	if candidate.Scope == string(config.ScopeLocal) {
		return filepath.Join(candidate.ProjectPath, ".claude", "skills")
	}
	return filepath.Join(config.ClaudeHome(), "skills")
}
